# Generated by Django 4.2.3 on 2024-05-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="unit_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
