version: '3.8'

services:
  my-postgres:
    image: postgres:15
    container_name: my-postgres
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"
        ] # Check if Postgres is ready 
      interval: 5s # Check every 10 seconds
      timeout: 5s # Wait for 5 seconds for response
      retries: 5 # Try 5 times before considering unhealthy

  web:
    image: darakhshanf/django-ecomm-cwk-app-ma
    platform: linux/amd64
    container_name: django
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py shell -c \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(is_superuser=True).exists() or User.objects.create_superuser(email='$DJANGO_SUPERUSER_EMAIL', password='$DJANGO_SUPERUSER_PASSWORD')\" &&
        python manage.py runserver 0.0.0.0:8000
      "
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python manage.py check --database=default"
        ] # Custom command for Django health
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - DJANGO_ENV=${DJANGO_ENV}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    depends_on:
      my-postgres:
        condition: service_healthy
