# Generated by Django 5.0.3 on 2024-03-31 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_category_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the product name", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Provide a detailed description of the product",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Enter the product price",
                        max_digits=8,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this category is created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this category is updated",
                    ),
                ),
                (
                    "available",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck if the product is currently unavailable",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Enter the unique Stock-Keeping Unit (SKU) for the product",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        help_text="Enter the brand name of the product",
                        max_length=100,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload an image for the product",
                        null=True,
                        upload_to="product_images",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Enter the product weight in kilograms (optional)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True,
                        help_text="Enter the product dimensions (e.g., 10x20x30 cm)",
                        max_length=100,
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Enter the current stock quantity of the product",
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False,
                        help_text="Check to mark this product as featured",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Select the product category",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "products",
                "ordering": ["-created_at"],
            },
        ),
    ]
