# Generated by Django 5.0.3 on 2024-03-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Enter the Tag name", max_length=255),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A unique slug for the Tag (no spaces or special characters)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this tag is created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="The date and time this tag is updated"
                    ),
                ),
            ],
        ),
    ]
