# Generated by Django 5.0.3 on 2024-03-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"], "verbose_name_plural": "tags"},
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the relevant tags for this product",
                related_name="products",
                to="products.tag",
            ),
        ),
    ]
