# Generated by Django 5.0.3 on 2024-03-31 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_tag_options_product_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Provide your thoughts about the product here"
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True,
                        help_text="The date and time this review is created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(
                        auto_now=True,
                        help_text="The date and time this review is updated",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="User submitting the review",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Select the product for reviewing",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "reviews",
                "ordering": ["author"],
            },
        ),
    ]
