# Generated by Django 4.2.3 on 2024-05-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="{% static 'assets/imgs/shop/product-solar-1-1.png' %}",
                help_text="Upload an image for the product",
                null=True,
                upload_to="product_images",
            ),
        ),
    ]
